### ISSUE TITLE
VirtualRouter.Interface is None with PA VM-50 v8.1.0

### ISSUE THREAD

**Issue by darren-jones-nz** [PaloAltoNetworks/pan-os-python#113]
**Problem:**
When iterating through VRs the interfaces are seemingly None

**VR Config Taken from "show config running":**
```
          Internet_eBGP {
            interface [ ethernet1/1 loopback.1];
          }
```

**Reproduction:**
Firstly have a PA VM-50 running v8.1.0, Create a VR, Add some interfaces to the VR.
The following code should list the interfaces; it does not.
```
#!/usr/bin/env python

from pandevice import device
from pandevice import firewall
from pandevice import network


HOSTNAME = '127.0.0.1'
USERNAME = 'admin'
PASSWORD = 'admin'


def main():
    fw = firewall.Firewall(HOSTNAME, USERNAME, PASSWORD)
    print('Firewall system info: {0}'.format(fw.refresh_system_info()))
    print('\n--------\n')

    routers = network.VirtualRouter.refreshall(fw, name_only=True)
    for vr in routers:
        print('Found the following VR: {0}'.format(vr.name))
        print('\n--------\n')

        if vr.interface is not None:
           for intf in vr.interface:
               print('Found the following Interface: {0}'.format(intf.name))

    print('Done!')


if __name__ == '__main__':
    main()
```

**Comment by btorresgil** [comment]
Hello.  You're using `name_only=True` in the `refreshall()` method.  This pulls only the names of the VirtualRouters from the firewall, not their properties.  So you won't get any of the interface information.  Remove the `name_only=True` and it should work fine.

FYI, `name_only=True` is most useful when you're trying to pull objects that have very large XML, but all you really need is a list of the objects to operate on.  A primary use case for this is when you need to know what vsys exist on a firewall, but you don't want to pull all the massive configuration within these vsys just to know that the vsys exist.  Let me know if any questions on this.

**Comment by btorresgil** [comment]
No problem!  Glad it's working!
