### ISSUE TITLE
Add Checksums to releases on GitHub

### ISSUE THREAD

**Issue by btorresgil** [PaloAltoNetworks/pan-os-python#119]
This is important to customers to verify that they got an accurate and complete copy of the library.

**Comment by ishuguru** [comment]
Excellent!

**Comment by ishuguru** [comment]
Any news regarding this?

**Comment by btorresgil** [comment]
PyPi is the primary release channel and it now offers hashes for all downloads.

See the 'View' button in the **Hashes** column on the right side:
https://pypi.org/project/pan-os-python/#files

GitHub offers a snapshot of the source automatically with each release but does not offer a hash. This is not under our control so we can't add a hash to the release asset files. But there are better ways to get the same thing with confirmation of a valid download.

1. `git clone` to get a confirmed valid snapshot of the source from GitHub.
2. Download the source from PyPi and verify the hash.
3. Download the wheel from PyPi and verify the hash.

This resolves the issue as customer can now verify an accurate download was successful. All interaction with PyPi as the release channel is automated so there is no risk of discrepancy between source code in GitHub and the corresponding PyPi files.

Closing this issue as there are now several preferred ways to validate a download without using the automatically generated GitHub source asset, which is not the recommended way to get pan-os-python anyway.
