### ISSUE TITLE
Panorama to commit 'templates'

### ISSUE THREAD

**Issue by irom77** [PaloAltoNetworks/pan-os-python#17]
When I commit from Panorama to the 'device group' it doesn't include 'templates' so how I actually commit 'templates' (network and device settings etc) ?

`pano.commit_all(devicegroup="PROD")`

With above I can only commit policy and object changes

**Comment by btorresgil** [comment]
Template commits are not directly supported in the `commit_all` method yet, but its something we're working on and should be available soon.  We'll use this issue to track progress.

In the meantime, you can use the `cmd=` argument to accomplish this with the raw commit XML.  For example:

To commit template 'abc':

    from pandevice import panorama
    pano = panorama.Panorama('10.0.0.5', 'admin', 'password')
    pano.commit_all(cmd="<commit-all><template><name>abc</name></template></commit-all>")

To commit devicegroup 'xyz' and include templates:

    from pandevice import panorama
    pano = panorama.Panorama('10.0.0.5', 'admin', 'password')
    pano.commit_all(cmd="<commit-all><shared-policy><include-template>yes</include-template><device-group><entry name='xyz'/></device-group></shared-policy></commit-all>")

**Comment by shinmog** [comment]
Including templates in the Panorama commit is now a boolean flag you can specify.  This issue should be resolved at this point.  Can you confirm, @irom77 ?

**Comment by shinmog** [comment]
This was fixed by #220 - closing this issue
