### ISSUE TITLE
_set_inner_xml_tag_text uses ascii encoding

### ISSUE THREAD

**Issue by megakoresh** [PaloAltoNetworks/pan-os-python#200]
## Describe the bug

When calling `.element_str()` in python 2 if any objects have non-ascii characters, the script will always crash.

## Expected behavior

Element is returned as xml string

## Current behavior

Crashes on python 2:

```
Traceback (most recent call last):
  File "./scripts/security_rules.py", line 182, in <module>
    main()
  File "./scripts/security_rules.py", line 126, in main
    as_dict = json.loads(json.dumps(xmltodict.parse(rule.element_str())['entry']))
  File "/Library/Python/2.7/site-packages/pandevice/base.py", line 2345, in element_str
    return ET.tostring(self.element(), encoding='utf-8')
  File "/Library/Python/2.7/site-packages/pandevice/base.py", line 2204, in element
    self.xml_merge(ans, itertools.chain(*iterchain))
  File "/Library/Python/2.7/site-packages/pandevice/base.py", line 1422, in xml_merge
    for e in elements:
  File "/Library/Python/2.7/site-packages/pandevice/base.py", line 2198, in <genexpr>
    (p.element(self._root_element(), settings, comparable) for p in paths),
  File "/Library/Python/2.7/site-packages/pandevice/base.py", line 2633, in element
    self._set_inner_xml_tag_text(e, value, comparable)
  File "/Library/Python/2.7/site-packages/pandevice/base.py", line 2769, in _set_inner_xml_tag_text
    elm.text = str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 33: ordinal not in range(128)
```

## Possible solution

`_set_inner_xml_tag_text` method in `base.py` must explicitly specify encoding as `utf8` (`elm.text = unicode(value)`) or maintainers of the library must officially declare that python 2 is not supported.

## Steps to reproduce

1. Create object in PanOS with non-utf characters in name or any of the attributes.
2. Write code to obtain the object

```python
device = base.PanDevice.create_from_device(args['ip'], api_key=args['key'])
rulebase = policies.Rulebase()
rulebase.element_str()
```

3. Run the code with python 2

## Screenshots

N/A

## Context

I am trying to run automation scripts on shitty old python version I cannot upgrade due to enterprise restrictions.

## Your Environment

- Version used: 8.0.1
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): python 2.7.16
- Operating System and version (desktop or mobile): RHEL 7.7
- Link to your project: N/A

**Comment by btorresgil** [comment]
Thanks for bringing this up.  We're not planning to make any more python 2 related fixes since python 2 is EOL. Is there any reason you must use python 2 and can't use python 3?

**Comment by megakoresh** [comment]
> Thanks for bringing this up. We're not planning to make any more python 2 related fixes since python 2 is EOL. Is there any reason you must use python 2 and can't use python 3?

Reason is that we have to use RHEL which doesn't support Python 3 until RHEL 8 (unless you use RHSC which are unusable garbage), our management infrastructure is outdated and there are no resources available to upgrade it to RHEL8 since there's too much stuff to migrate. In other words - same as everywhere else.

If you officially declare that you don't support Python 2 that might provide more motivation for people actually hurry up with the upgrades.

**Comment by shinmog** [comment]
RHEL 8 is released, and python2 has long since been EOLed.  Closing this issue out.
