### ISSUE TITLE
Needs a nice way to add Panorama audit comments to policy changes

### ISSUE THREAD

**Issue by dataway** [PaloAltoNetworks/pan-os-python#209]
### Is your feature request related to a problem?

Our Panorama setup requires audit comments for any policy changes. Currently, pandevice doesn't offer any good way to set them.

Currently I'm doing this with hand written XML along the following lines:
```
panorama = pandevice.panorama.Panorama()
rule = pandevice.policies.SecurityRule()
...
rule.description = 'Alteration'
rule.update('description')
comment = "Audit comment"
panorama.op('<set><audit-comment><xpath>{0}</xpath><comment>{1}</comment></audit-comment></set>'.format(rule.xpath(), comment), cmd_xml=False)
```
### Describe the solution you'd like

An API along the lines of
`rule.audit_comment("Audit comment")`
which would perform the correct operation.

### Describe alternatives you've considered

Already using the aforementioned, ugly code.

**Comment by shinmog** [comment]
Once #310 is finalized, the intent is that this will be added next.
