### ISSUE TITLE
HOW TO GET HIT COUNT

### ISSUE THREAD

**Issue by EdoardoMDP** [PaloAltoNetworks/pan-os-python#239]
Hi all,

Is there a method to get hit count value?

Thanks

**Comment by ishuguru** [comment]
I have also looked around but cant find anything

**Comment by rebelfish** [comment]
You can get rule hit count using 'op'.
Build the base object:
>>> pandev = base.PanDevice.create_from_device(<panorama/firewall>, api_username=<username>, api_password=<password>)
>>> dg = 'My Device Group'
>>> rule = 'My Rule Name'
>>> cmd_rule-hit-count = '<show><rule-hit-count><device-group><entry name="{0}"><pre-rulebase><entry name="security"><rules><rule-name><entry name="{1}"/></rule-name></rules></entry></pre-rulebase></entry></device-group></rule-hit-count></show>'.format(dg, rule)
>>> resp_rule-hit-count = pandev.op(cmd=cmd_rule-hit-count, cmd_xml=False)
This will pull the rule hit count data for each firewall in the device group and the tree will look like:
<response status="success">
	<result>
		<rule-hit-count>
			<device-group>
				<entry name="My Device Group">
					<rule-base>
						<entry name="security">
							<rules>
								<entry name="My Rule Name">
									<device-vsys>
										<entry name="My Device Group/<firewall 1 serial>/vsys1">
											<hit-count />
											<last-hit-timestamp />
											<last-reset-timestamp />
											<first-hit-timestamp />
											<last-receive-timestamp />
											<device-state>yes</device-state>
										</entry>
										<entry name="My Device Group/<firewall 2 serial/vsys2">
											<hit-count />
											<last-hit-timestamp />
											<last-reset-timestamp />
											<first-hit-timestamp />
											<last-receive-timestamp />
											<device-state>yes</device-state>
										</entry>
									</device-vsys>
								</entry>
							</rules>
						</entry>
					</rule-base>
				</entry>
			</device-group>
		</rule-hit-count>
	</result>
</response>
