### ISSUE TITLE
Comments are missing

### ISSUE THREAD

**Issue by xod442** [PaloAltoNetworks/pan-os-python#242]
## Describe the bug

I use the layer3 subinterface method in pandevice library and pass several variables to it. They all show up in the GUI except for the comment. 

## Expected behavior

When I pass the comment variable via python, I expect the comment to show up in the sub interface details in the GUI 

## Current behavior

The comment field never changes. It is always blank

## Possible solution

Every other variable I pass gets added to the interface and shows up in the GUI

## Steps to reproduce

run the script I created. each sub interface is created with MTU and IP and tag. No comment field. 

## Context

Processing 250 sub interfaces and I need the comments for each one.

## Your Environment

Palo Alto VM on AWS 9.1, Python 2.7, Ubuntu Mate 

https://github.com/xod442/palo-alto-dev/blob/master/issue.py

![comment](https://user-images.githubusercontent.com/10523121/87100527-76ac9880-c201-11ea-8910-ac36211476d8.png)

**Comment by shinmog** [comment]
@xod442 

Seems this issue is invalid.  The comment is being assigned as a positional argument, 4th index, in the script linked.  The comment field is actually in the 9th argument position.  I'd recommend assigning the comment doing `comment=comment`.

**Comment by shinmog** [comment]
Seems this issue is resolved, so closing it out.
