### ISSUE TITLE
Add support for group-tag

### ISSUE THREAD

**Issue by rokkberr** [PaloAltoNetworks/pan-os-python#248]
### Is your feature request related to a problem?

In my department we have decided to use the group-tag atrribute to visualise grouping of security rules in Panorama.

I can set this atrribute in Panorama GUI and CLI, but it doesn't seem to be attached to the SecurityRule object in panos.

### Describe the solution you'd like

The addition of a parameter, group-tag, of type str in the different kinds of Rules in policies. Or maybe in VersionedObject. I'm not an experienced enough developer to know which is best :)

### Describe alternatives you've considered

I've considered manually adding the tag through the CLI or possibly using API call URI's. Those are perfectly nice workaround, but they are workarounds.

### Additional context

![image](https://user-images.githubusercontent.com/32454187/89271615-3fcd7500-d63d-11ea-860a-b428c8cccad2.png)
![image](https://user-images.githubusercontent.com/32454187/89271759-73100400-d63d-11ea-9727-8ddf63e791d5.png)

**Comment by mgollo** [comment]
I would also love this feature to be added.

Thanks,
Martin
