### ISSUE TITLE
Need FQDN Support for IKE Gateway Peer IP Address

### ISSUE THREAD

**Issue by mrichardson03** [PaloAltoNetworks/pan-os-python#250]
### Is your feature request related to a problem?

FQDN support for IKE gateways is missing in pan-os-python.  This was supported starting in [PAN-OS 8.1](https://docs.paloaltonetworks.com/pan-os/8-1/pan-os-new-features/networking-features/fqdn-support-for-ike-gateway-peer-ip-address.html).

### Describe the solution you'd like

`peer_ip_type` needs to also accept `fqdn`, and `peer_ip_value` needs to be adjusted as well.

### Additional context

We need this to add support in the Ansible module: https://github.com/PaloAltoNetworks/pan-os-ansible/issues/10

**Comment by btorresgil** [comment]
@mrichardson03 PR created for this. Check it out and let us know how it looks.

**Comment by mrichardson03** [comment]
> @mrichardson03 PR created for this. Check it out and let us know how it looks.

Works great, thanks!
