### ISSUE TITLE
Execute configuration mode commands with op function (operational commands)

### ISSUE THREAD

**Issue by bvaradinov-c** [PaloAltoNetworks/pan-os-python#254]
## Describe the problem
I'm looking into the documentation for the operational commands
Perform operational commands using the op method on a PanDevice. The return value is an xml.etree.ElementTree object:
element_response = fw.op('show system info')
Use the xml argument to return a string with xml:
xml_response = fw.op('show system info', xml=True)

Is it possible to use configure mode for those operational commands. If not, please share how can be executed configure mode command with pan-os-python.

**Comment by btorresgil** [comment]
Thanks for asking your question. I just created PR #255 with documentation improvements

Here's the proposed new documentation, please let me know if it is clear enough and I will merge it in:
https://pan-os-python--255.org.readthedocs.build/en/255/getting-started.html#operational-commands

**Comment by bvaradinov-c** [comment]
This looks ok. However, I was able to install plugin with op commands so it is not just get and clear.

Also I'm interested if there is an alternative to execute commands in configure mode? I knowt that the project provides you a flexible object model but there could be operations which are only available only trough the cli configure mode commands.

**Comment by btorresgil** [comment]
Thanks for the feedback. I'll clarify the op commands better.

There is no way to send config mode set commands (or even op commands) to the API directly. We are able to translate op commands to XML, but we can't do that with config mode commands. You can use the object model to build the configuration, or you can build the XML yourself and send it using the `fw.xapi.set()` and `fw.xapi.edit()` methods.

Hope that answers your questions.
