### ISSUE TITLE
Support for audit comments on rules

### ISSUE THREAD

**Issue by stealthllama** [PaloAltoNetworks/pan-os-python#272]
### Is your feature request related to a problem?

Need the ability to add and retrieve audit-comments on all rulebases.  This is supported in PAN-OS 9.0+

### Describe the solution you'd like

The `audit-comment` could be an additional parameter used when creating or modifying a rule.

### Describe alternatives you've considered

N/A

### Additional context

It would be beneficial to extend audit-comment support to the SDK for Ansible and other tools.

**Comment by GangQ** [comment]
since security requires 'audit comments' in policy creation, we have to have this.  

does anyone know if there is a workaround with existing modules?

**Comment by madmann26** [comment]
I will have to hard echo this.

The only way to do that right now is with clunky, syntax error prone xpath.

It would be nice to be able to do this at a per-rule level, that way I can parse it out of my csv when I create/modify a rule.

However, I would think that this would need restapi support first. When you look at the restapi-doc, there is nothing there at a per-rule level (pre, post, shared).

**Comment by shinmog** [comment]
Once #310 is finalized, the intent is that this will be added next.
