### ISSUE TITLE
NatRule: missing dynamic destination support

### ISSUE THREAD

**Issue by mrichardson03** [PaloAltoNetworks/pan-os-python#283]
### Is your feature request related to a problem?

Does not look like NatRule supports the 'Dynamic IP (with session distribution)' translation type.  This is needed for https://github.com/PaloAltoNetworks/pan-os-ansible/issues/146.

**Comment by shinmog** [comment]
It's there, just not documented:  #314

**Comment by shinmog** [comment]
Fixed by #314
