### ISSUE TITLE
Need Help configuring NatRule Using Pan OS python

### ISSUE THREAD

**Issue by bangi123** [PaloAltoNetworks/pan-os-python#284]
Hi Team, 

I tried configuring NatRule with Pan OS Python. But failued. Can you please provide an example to configure Nat Rule. 
I am able to read NatRules But cannot configure Nat Rules.

Thanks, 
Raju

**Comment by shinmog** [comment]
You add rules onto a `Rulebase` / `PreRulebase` / `PostRulebase` object.  Refer to this example script (it shows security rules, logic is the same).

**Comment by shinmog** [comment]
Eerr, let me try giving the script this time:

https://github.com/PaloAltoNetworks/pan-os-python/blob/develop/examples/ensure_security_rule.py
