### ISSUE TITLE
Add patameter 'type="URL List" or "Category Match"' for panos.objects.CustomUrlCategory

### ISSUE THREAD

**Issue by Konakin** [PaloAltoNetworks/pan-os-python#285]
Hello.

## Describe the bug

When i create panos.objects.CustomUrlCategory with parameter "url_value", i have error "panos.errors.PanDeviceXapiError:  Black list internal URL -> list 'http://example.ru' is invalid. custom-url-category entry has to be type specified
 Black list internal URL -> list is invalid".

## Expected behavior

In class panos.objects.CustomUrlCategory need set parameter type (URL List or Category Match).

## Current behavior

If i send comand (panos.objects.CustomUrlCategory('Black list internal URL')) without parameter url_value (only with name), i don't have error. 

And when i set type "URL List" for UrlCategory in web concole and next send comand with url_value (panos.objects.CustomUrlCategory('Black list internal URL', url_value=ioc)), i don't have error.

## Possible solution

Add new parameter call type with value "URL List or Category Match"' for class panos.objects.CustomUrlCategory

## Steps to reproduce

code with error:
```
from panos import firewall
import panos.objects
ioc=['http://example.com']
fw = firewall.Firewall(hostname, api_username=user, api_password=password)
h=panos.objects.CustomUrlCategory()
fw.add(h)
current=panos.objects.CustomUrlCategory.refreshall(h)
temp1=panos.objects.CustomUrlCategory('Black list internal URL', url_value=ioc)
fw.add(temp1)
temp1.create()
```

## Context

I need create CustomUrlCategory, add url, and add CustomUrlCategory in security rule.

## Your Environment

- Version used:
- (python 3.9:
- Operating System (Windows 10 or cent os 7)
- Link to your project: https://github.com/TheHive-Project/Cortex-Analyzers/pull/886

**Comment by shinmog** [comment]
The `type` param was added already as part of #244
