### ISSUE TITLE
PanSessionTimedOut and I think it's because there's no graceful disconnect? 

### ISSUE THREAD

**Issue by tom0010** [PaloAltoNetworks/pan-os-python#289]
## Describe the bug
I have a script that is monitoring the CPU cores in a PA device using the API call.
This gets executed every 10 seconds or so, and I think the sessions are not closing cleanly, therefore that is why I think I am seeing this issue. 
I tried to look through the code but I couldn't see anything about a disconnect.
In Netmiko for example, there is a function to disconnect the session. Now, I'm not sure if that is even needed here but I am lost if that is not the case. 

## Expected behavior
For the device to not timeout.

## Current behavior
I am getting: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/panos/base.py", line 3626, in method
    super_method(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pan/xapi.py", line 951, in op
    self.__type_op(cmd, vsys, extra_qs)
  File "/usr/lib/python3.8/site-packages/pan/xapi.py", line 974, in __type_op
    raise PanXapiError(self.status_detail)
pan.xapi.PanXapiError: Session timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python-modules/paloalto.py", line 32, in main
    output = device.op(command, xml=True, cmd_xml=False)
  File "/usr/lib/python3.8/site-packages/panos/firewall.py", line 207, in op
    return super(Firewall, self).op(
  File "/usr/lib/python3.8/site-packages/panos/base.py", line 3774, in op
    element = self.xapi.op(
  File "/usr/lib/python3.8/site-packages/panos/base.py", line 3645, in method
    raise the_exception
panos.errors.PanSessionTimedOut: Session timed out
```

## Possible solution
Add a function to gracefully disconnect the session.

## Steps to reproduce
Run every 10-30 seconds:
```
    device = firewall.Firewall(host, username, password, timeout=120, is_virtual=False, interval=10)
    command = ("<show><running><resource-monitor><minute><last>1"
               "</last></minute></resource-monitor></running></show>")
    output = device.op(command, xml=True, cmd_xml=False)
    output = xmltodict.parse(output)
```
I'm currently using telegraf to execute this multiple times.

## Context
Trying to monitor DP cores and put the info into a timeseries DB.

## Your Environment

- Version used: 1.16.2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): python3.8
- Operating System and version (desktop or mobile): Docker Alpine 3.12.1
- Link to your project: NA

**Comment by tom0010** [comment]
As a test, I switched over to using just python `requests`. I'm still getting some timeouts but no where near as many.

09:57:01,529 root DEBUG OrderedDict([('response', OrderedDict([('@status', 'unauth'), ('@code', '22'), ('msg', OrderedDict([('line', 'Session timed out')]))]))])

Not sure if you would like to investigate further or not. 
Happy to send more info if needed.

**Comment by btorresgil** [comment]
Hi @tom0010, sorry for the slow response, and happy holidays. Since this is happening outside the pan-os-python library, I recommend to open a TAC case to investigate. The PAN-OS API is a TAC supported product and they can look into why your sessions are timing out.

I'll close this issue for now, since it doesn't seem specific to the pan-os-python library. Thanks for following up.
