### ISSUE TITLE
How to Add/On board bulk New firewall devices via API to panorama ?

### ISSUE THREAD

**Issue by KedharnathGoud** [PaloAltoNetworks/pan-os-python#294]
We are trying to add the PAN firewalls to the panorama manually and  we are trying to automate this process .

Can anyone provide API to add bulk devices to panorama  ?

**Comment by btorresgil** [comment]
You can add firewalls to panoramas and to device groups. For example:

Add a firewall to Panorama:
```python
from panos.panorama import Panorama
from panos.firewall import Firewall

pano = Panorama("10.0.0.10", "admin", "password")
fw1 = Firewall(serial="1234567890")
pano.add(fw1)
fw1.create()
```

Add a firewall to a new device group:
```python
from panos.panorama import Panorama, DeviceGroup
from panos.firewall import Firewall

pano = Panorama("10.0.0.10", "admin", "password")
dg = DeviceGroup("MyDG")
fw1 = Firewall(serial="1234567890")
pano.add(dg).add(fw1)
dg.create()
fw1.create()
```

**Comment by btorresgil** [comment]
Questions like this are best asked in the new [GitHub Discussions](https://github.com/PaloAltoNetworks/pan-os-python/discussions). I'll close this issue for now, but you can open a discussion if you have any follow up questions. Thanks!
