### ISSUE TITLE
Pulling Rulebase and Security Policies 

### ISSUE THREAD

**Issue by sonicshrub** [PaloAltoNetworks/pan-os-python#308]
## Documentation link

https://github.com/PaloAltoNetworks/pan-os-python/blob/master/examples/ensure_security_rule.py

## Describe the problem

Hi team, I am not sure if this is a bug or a documentation/user issue.  I am trying to use python to pull rulebase information from firewalls.  This works for a PA-200 and a PA-VM, both have a trivial number of firewall rules, however I cannot get the same code to retrieve rulebase on any other firewalls in our enterprise.

I spoke with PA TAC about this and was told TAC does not support API usage and to turn to the Github community.  Here I am…

Not sure if I am missing something critical with the code or if there is a bug.   I can retrieve sys_config data from all firewalls I have tried however the rule base only works on 2 firewall out of many I have tried

## My Setup:
Jupyter Notebook : The version of the notebook server is: 6.0.3
Python: Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

Using this example script as my guide https://github.com/PaloAltoNetworks/pan-os-python/blob/master/examples/ensure_security_rule.py

## What I am seeing
Example of a working Device:

Model: PA-VM; Version: 8.1.16; vsys: off
Sirius Access
Azure to Office VPN
VPN Traffic
To Panorama
TEST with VINCENT
CLEANUP RULE

Examples of a non working devices:

Model: PA-3050; Version: 8.1.16; vsys: off; HA: active
Model: PA-3220; Version: 8.1.16; vsys: off; HA: disabled
Model: PA-5020; Version: 8.1.16; vsys: off; HA: active
Devicename :France-Paris-PA2; Model: PA-220; Version: 8.1.16; vsys: off; HA: passive
Devicename :France-Paris-PA1; Model: PA-220; Version: 8.1.16; vsys: off; HA: active;

##Code I am using

from panos import panorama
from panos import firewall

pano = panorama.Panorama("172.21.x.z", "xxxxxx", 'pppppp')

fw_test = firewall.Firewall(serial="###########")

pano.add(fw_test)

sys_info__ = fw_test.show_system_info()
appVersionDate = sys_info__['system']['app-release-date']
avVersionDate = sys_info__['system']['av-release-date']
threatVersionDate = sys_info__['system']['threat-release-date']
wfVersionDate = sys_info__['system']['wildfire-release-date']
fw_devicename = sys_info__['system']['devicename']
fw_hostname = sys_info__['system']['hostname']
fw_sw_version = sys_info__['system']['sw-version']
fw_hw_model = sys_info__['system']['model']
fw_serial = sys_info__['system']['serial']
fw_ip_address = sys_info__['system']['ip-address']
fw_vsys = sys_info__['system']['multi-vsys']
fw_vpn_version = sys_info__['system']['global-protect-client-package-version']
urlVersionDate = sys_info__['system']['url-filtering-version']

HA = fw_test.show_highavailability_state()

#print sysinfo

print("Devicename :" + fw_devicename + "; Model: " + fw_hw_model + "; Version: " + fw_sw_version + "; vsys: " + fw_vsys + "; HA: " + str(HA[0]) + "; IP: " + str(fw_ip_address))

#print rules

rulebase = panos.policies.Rulebase()

fw_test.add(rulebase)

current_security_rules = panos.policies.SecurityRule.refreshall(rulebase)
is_present = False
for rule in current_security_rules:
print(rule.name)

**Comment by shinmog** [comment]
The code doesn't have any errors that I can see.

One thing you don't discuss is your setup.  If your intention is to get all the security rules the firewall is implementing, this won't happen with the above code.  The Pre and Post rules coming from Panorama will not come as a part of this `refreshall()` - you need to get those rules from Panorama itself.

**Comment by sonicshrub** [comment]
Hi Shinmog, thanks for your response.

You are correct…. My intent is to get all the security rules from the firewall.  I do not really care how I do this, however I was trying to proxy through Panorama to leverage a centralized account/password.

I neglected to mention earlier that I have also attempted at connect directly to firewalls, not involve Panorama, to collect the security rules where I do have access, using the following:
`fw_test = firewall.Firewall(172.21.x.z, xxxxxxx, pppppp)`
instead of 
`pano = panorama.Panorama("172.21.x.z", "xxxxxx", 'pppppp')
fw_test = firewall.Firewall(serial="###########")
pano.add(fw_test)`

This results in an empty list with the exception of the two examples I mentioned earlier. 

Admittedly it has been several years since I have administered a firewall(I am an auditor now) and I am not very familiar with Panorama, Pre/Post Rules, much less how to leverage pan-os-python through Panorma. 

To your question on the setup, our firewall management team has told me that almost all firewalls are managed through Panorama using PreRules and that PostRules are not used.  I have access to Panorama and can see all the devices from this pain of glass. I was really hoping to be able to use python to gather rulebase similar to using "show running security-policy" on a firewall however I am seeing that this is more complicated than I expected compared to gathering other firewall data like local users, sysinfo, etc 

Should I be able to pull security rules with the above code if I connect directly to the firewall with pan-python and considering that Panorama is managing the firewall?  

Based on your feedback I am now trying to pull the PreRule data from Panorama however I am a bit lost in the configuration tree and with the device groups.  I am currently working through the Lesson5 Panorma (https://github.com/PaloAltoNetworks/pandevice-tutorial) in an attempt to RTFM before I ask for help. Currently I see a tree similar to this  Panorama: IP -> DeviceGroup: 1-10  -> Firewall: SN 1-10 -> SystemSettings  however I am not sure how to pivot this into enumerating security rules just yet.

Again thank you for your time and apologies in advance if this is more of an educational issue than a bug or documentation

**Comment by sonicshrub** [comment]
Posting progress in case this may help someone else.  There may be a better way to do this but this seems to have worked.  .tree() was invaluable at helping me determine what was going on with the configuration tree as I was hacking through this. 

from panos import panorama
from panos import policies 
pano = panorama.Panorama("hostname", "account", 'password')

Building tree with known devicegroup:

dg = panorama.DeviceGroup('Prague-PA1')
pano.add(dg)
prerulebase = policies.PreRulebase(dg)
postrulebase = policies.PostRulebase(dg)
dg.add(prerulebase)
dg.add(postrulebase)

Pulling PreRules:
current_security_pre_rules = policies.SecurityRule.refreshall(prerulebase)

Pulling NAT rules:
current_nat_pre_rules = policies.NatRule.refreshall(prerulebase)

I am still unclear why I am unable to proxy through Panorama to pull the local firewall rules. 

Also it would be great to see the documentation grow to include more examples around NAT and retrieving current configuration (firewall policy, NAT, syslog, NTP, etc) directly or via Panorama.  Much of the focus seems to be on commits to the devices as opposed to retrieving existing configuration.  

All that said, this is a great project and thank you to the team behind the scenes who has put it all together.

**Comment by shinmog** [comment]
@sonicshrub 

Glad you got it working.  So just to level set, this gets the security rules locally defined on the firewall itself:

```python
from panos.firewall import Firewall
from panos.policies import Rulebase, SecurityRule

fw = Firewall(host, user, passwd)
rb = Rulebase()

fw.add(rb)

rules = SecurityRule.refreshall(rb)
```

If you know that the above firewall is in device group "foo" on Panorama, then you can get the pre-rulebase security rules like so:

```python
from panos.panorama import Panorama, DeviceGroup
from panos.policies import PreRulebase, SecurityRule

pano = Panorama(host, user, passwd)
dg = DeviceGroup("foo")
rb = PreRulebase()

pano.add(dg)
dg.add(rb)

rules = SecurityRule.refreshall(rb)
```

The reason that you don't get all rules (read:  rules locally defined AND rules pushed from Panorama) on the firewall when you do that first chunk of code is that the Panorama rules are stored at a different XPATH internally.  If you query the correct XPATH on the firewall you will in fact see the security rules pushed down from Panorama to the firewall, but there is currently no support for querying the firewall for Panorama pushed config.

The expectation is that if you want Panorama config you should ask Panorama for that information, and if you want (locally configured) firewall config, you ask the firewall for that.

I hope this helps clarify things.

**Comment by shinmog** [comment]
Answered the question so closing out this issue.

**Comment by Wyko** [comment]
From what I've gathered around the internet, it's not possible to query a `Panorama` for security rule hit counts. The only way is to query a `Firewall` directly. I'm trying to get hit counts for `Panorama`-defined rules. Since they don't show up in the output, I'm not sure how to access the hit counts.

This seems like a good use case for adding pushed rules to the output.
