### ISSUE TITLE
Feature: add support for Rip profile configuration 

### ISSUE THREAD

**Issue by markharden817** [PaloAltoNetworks/pan-os-python#329]
### Is your feature request related to a problem?

Currently there is no supported methods for configuring RIP routing on a virtual router using this library.  This functionality is required in our current network design and would be a useful feature to implement. 

### Describe the solution you'd like

I should be able to instantiate a Rip class object and add it to a VirtualRouter instance to configure device. Ideally it should function the same as all other VirtualRouter children.

### Describe alternatives you've considered

Currently I am utilizing the pan.xapi.PanXapi library to interface with the firewall for RIP routing as a workaround.

**Comment by shinmog** [comment]
Fixed by #330
