### ISSUE TITLE
Op commands don't support Plugin

### ISSUE THREAD

**Issue by danquack** [PaloAltoNetworks/pan-os-python#352]
## Describe the bug
Looking to configure a plugin on the vm_series. When I execute op command it doesn't doesn't support the `request` parameter. This is not specific to the plugin Im working with, but Ive included that below in the steps below as a test case. Im not really sure what category this would fall into from an issue perspective. 

## Expected behavior
request command works

## Current behavior

```
 PanDeviceXapiError:  request -> plugins -> vm_series -> aws -> gwlb -> inspect -> enable is invalid
```

## Steps to reproduce

1. Create firewall api object 
2. Use the operation command with `api.op("request plugins vm_series aws gwlb inspect enable yes")`

## Your Environment

- Version used: 1.3.0
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): python3.8
- Operating System and version (desktop or mobile): 
- Link to your project:

**Comment by shinmog** [comment]
What is the XML you're trying to send?  If you're unsure, you can use the CLI to do `debug cli on` and it will show the XML.

With the `op()`, you need to double quote stuff that is sent as arg values.  Looking at the command, at the very least you probably need to be doing this:

```python
fw.op('request plugins vm_series aws gwlb inspect enable "yes"')
```

I just don't know if more needs to be quoted or not.

**Comment by danquack** [comment]
@shinmog The output returns:

```
> request plugins vm_series aws gwlb inspect enable yes
(container-tag: plugins container-tag: vm_series container-tag: aws container-tag: gwlb container-tag: inspect leaf-tag: enable value: yes pop-tag: pop-tag: pop-tag: pop-tag: pop-tag:)
((eol-matched: . #t) (context-inserted-at-end-p: . #f))


<request cmd="op" cookie="xxxx" uid="1000"><operations><request><plugins><vm_series><aws><gwlb><inspect><enable>yes</enable></inspect></gwlb></aws></vm_series></plugins></request></operations></request>
````

Ive tried just taking that exact output and piping it to the api, and I either get `panos.errors.PanURLError: URLError: code: 400 reason: Request is not a valid XML` or by trimming it to just operations, it tells me that's not valid if I do `panos.errors.PanDeviceXapiError:  operations  is unexpected`
