### ISSUE TITLE
add support for hit count in Panorama Object

### ISSUE THREAD

**Issue by devbollinger** [PaloAltoNetworks/pan-os-python#388]
### Is your feature request related to a problem?

I would like to gather hit_count for security rules from Panorama. I've seen this feature implemented with the Firawall object and I was wondering if we could do the same for the Panoram object. Unless I missed something it seems that there is nothing similar for panorama.

### Describe the solution you'd like

Something similar to this commit: https://github.com/PaloAltoNetworks/pan-os-python/commit/7a2e95b3746faeb386c58dedbb40b71d81a5cff0

### Describe alternatives you've considered

I could pass an xml to `Panorama.op` but I rather work with object.

I see a `panos.policies.RulebaseOpState` imbricated in SecurityRule response and I trying to leverage this with no success.
I want to be able to retrieve security rules and their associated hit_count. If a process already exist please let me know how to do it.

**Comment by shinmog** [comment]
This is present already, docs need to be clarified about opstate stuff.  Say you want hit count info for all pre-rulebase security rules in device group "myDg":


```python
from panos.panorama import Panorama, DeviceGroup
from panos.policies import PreRulebase, SecurityRule

pano = Panorama(....)

dg = DeviceGroup("myDg")
pano.add(dg)

base = PreRulebase()
dg.add(base)

info = dg.opstate.hit_count.refresh("security", all_rules=True)
```

If you just want hit count info for a specific rule, then use the `opstate.hit_count` on the object of that specific rule.

**Comment by devbollinger** [comment]
Hello @shinmog   
So I tried your code and I got an exception:  
`Traceback (most recent call last):
  File "api.py", line 19, in <module>
    info = device_group.opstate.hit_count.refresh("security", all_rules=True)
AttributeError: 'DeviceGroupOpState' object has no attribute 'hit_count'`

Here is my full code: 
`from panos.panorama import DeviceGroup, Panorama
from panos.policies import PostRulebase

pan = Panorama("hostname", "username", "pwd")

device_group = DeviceGroup("device group")
pan.add(device_group)

post_rule = PostRulebase()
device_group.add(post_rule)

info = device_group.opstate.hit_count.refresh("security", all_rules=True)
`
using pan-os-python==1.6.0

**Comment by shinmog** [comment]
My bad.  Looks like device groups don't have a hit count op state; individual rules do, and the rulebases do (policies.PreRulebase, policies.Rulebase, policies.PostRulebase).

**Comment by ajmartins** [comment]
Hi @shinmog, just following up on this. It appears I'm unable to get the hitcounts (updated version to 1.7.2).  

I tried the following but it returns an empty dictionary:

`from panos.panorama import Panorama, DeviceGroup
from panos.policies import PostRulebase, SecurityRule
 
us = "xxx"
pw = "xxx"
hn = "xxx"
pano = Panorama(hostname=hn, api_username=us, api_password=pw)
 
dg = DeviceGroup("my-DG")
pano.add(dg)
 
rb = PostRulebase()
pano.add(rb)
 
hc = rb.opstate.hit_count.refresh("security", all_rules=True)
print(hc.items())`

**Comment by kevinhuy** [comment]
hello @AnthoBalitrand 

the hit count seems to be track in rule usage in panorama.  
![image](https://user-images.githubusercontent.com/37373983/215110139-3261ca91-eb40-463f-b180-9d72c3651971.png)

**Comment by Wyko** [comment]
Any update on this? 
![image](https://github.com/PaloAltoNetworks/pan-os-python/assets/467094/53e9037f-a080-4ca1-84ad-f1d7c6c89724)
It's clearly possible to see hit counts via Panorama. If you log into it via CLI, and run this command, you can see the same data:
`show rule-hit-count device-group eagn.... post-rulebase security rules rule-name "MD..."`

But there isn't an obvious way to get this data via the API.

**Comment by SimoneR2** [comment]
I'm resuming this old issue because I encountered the same problem. As a workaround I found that is possibile to perform this action to get hitcount for rule. For example if I want to extract the hitcount for a rule in post-rulebase section for a device-group-name I can perform:

    xml_answer = panoramaclass.op(cmd="<show><rule-hit-count><device-group><entry name='**DEVICE_GROUP_NAME**'><post-rulebase><entry name='security'><rules><rule-name><entry name='**RULE-NAME**'/></rule-name></rules></entry></post-rulebase></entry></device-group></rule-hit-count></show>", cmd_xml=False, xml=False)

It will return an xml ElementTree that can be iterated. I'm not a guru in python so please correct my example:

    most_recent_hit = 0 #This is used to select the most recent hit from all the firewalls that form the device-group
    for elem in xml_answer.findall(".//last-hit-timestamp"):
        if most_recent_hit < int(elem.text):
             most_recent_hit = int(elem.text)`

I hope that this will help other users with the same issue.

**Comment by amruta-elisity** [comment]
@AnthoBalitrand /Team, i am unable to get the hit count from panorama even with latest panos-sdk. Are we planning to support this via API or it has to be fetched via CLI itself?.

My sample code:
```
def fetch_panorama_rules_with_hit_counts(panorama_ip, api_key, device_group_name):
    # Connect to Panorama
    panorama = Panorama(hostname=panorama_ip, api_key=api_key)

    # Create and add device group
    dg = DeviceGroup(name=device_group_name)
    panorama.add(dg)

    # Add rulebase to the device group
    rulebase = PreRulebase()
    try:
        dg.add(rulebase)
    except Exception as e:
        print(f"Error while adding rulebase: {e}")
        return []
    info = rulebase.opstate.hit_count.refresh("security", all_rules=True)
    print(vars(info["amruta-pre-rule"]))
```
Output:
```
{'obj': <SecurityRule amruta-pre-rule 0x71e341076170>, 'name': 'None', 'latest': None, 'hit_count': None, 'last_hit_timestamp': None, 'last_reset_timestamp': None, 'first_hit_timestamp': None, 'rule_creation_timestamp': 1750751413, 'rule_modification_timestamp': 1751350485}
```
On the other hand from CLI , i can see the hit count
```

show rule-hit-count device-group IoT_Firewalls pre-rulebase security rules all

Rule Name                                                         Rule usage          Device Name                         Vsys         Hit Count       Last Hit Timestamp            Last Reset Timestamp          First Hit Timestamp           Rule Create Timestamp        Rule Modify Timestamp         Last Received Update Timestamp          Device State     
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
amruta-pre-rule                                                  
                                                                  Used                PANW-BR2                            vsys1        320627          Wed Jul  2 04:49:39 2025      -                            Mon Jun 30 23:19:30 2025      Tue Jun 24 00:52:26 2025      Mon Jun 30 23:16:24 2025      Wed Jul  2 04:50:25 2025                connected        
Total Hit Count:     320627    
```

Disclaimer:
```
Fetching hit count via individual SecurityRule would be costly task and with policy scale it increases the complexity. 

"all_rules"=True was a better option
```

**Comment by remchuk** [comment]
> [@AnthoBalitrand](https://github.com/AnthoBalitrand) /Team, i am unable to get the hit count from panorama even with latest panos-sdk. Are we planning to support this via API or it has to be fetched via CLI itself?.
> 
> My sample code:
> 
> ```
> def fetch_panorama_rules_with_hit_counts(panorama_ip, api_key, device_group_name):
>     # Connect to Panorama
>     panorama = Panorama(hostname=panorama_ip, api_key=api_key)
> 
>     # Create and add device group
>     dg = DeviceGroup(name=device_group_name)
>     panorama.add(dg)
> 
>     # Add rulebase to the device group
>     rulebase = PreRulebase()
>     try:
>         dg.add(rulebase)
>     except Exception as e:
>         print(f"Error while adding rulebase: {e}")
>         return []
>     info = rulebase.opstate.hit_count.refresh("security", all_rules=True)
>     print(vars(info["amruta-pre-rule"]))
> ```
> 
> Output:
> 
> ```
> {'obj': <SecurityRule amruta-pre-rule 0x71e341076170>, 'name': 'None', 'latest': None, 'hit_count': None, 'last_hit_timestamp': None, 'last_reset_timestamp': None, 'first_hit_timestamp': None, 'rule_creation_timestamp': 1750751413, 'rule_modification_timestamp': 1751350485}
> ```
> 
> On the other hand from CLI , i can see the hit count
> 
> ```
> 
> show rule-hit-count device-group IoT_Firewalls pre-rulebase security rules all
> 
> Rule Name                                                         Rule usage          Device Name                         Vsys         Hit Count       Last Hit Timestamp            Last Reset Timestamp          First Hit Timestamp           Rule Create Timestamp        Rule Modify Timestamp         Last Received Update Timestamp          Device State     
> ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> amruta-pre-rule                                                  
>                                                                   Used                PANW-BR2                            vsys1        320627          Wed Jul  2 04:49:39 2025      -                            Mon Jun 30 23:19:30 2025      Tue Jun 24 00:52:26 2025      Mon Jun 30 23:16:24 2025      Wed Jul  2 04:50:25 2025                connected        
> Total Hit Count:     320627    
> ```
> 
> Disclaimer:
> 
> ```
> Fetching hit count via individual SecurityRule would be costly task and with policy scale it increases the complexity. 
> 
> "all_rules"=True was a better option
> ```

Any updates regarding this?
