### ISSUE TITLE
Security Zones List - Panorama

### ISSUE THREAD

**Issue by FrancisPrakash** [PaloAltoNetworks/pan-os-python#389]
Unable to fetch Security Zones list from Panorama, the below code returns empty list.

pano = Panorama(PANORAMA_IP, PANORAMA_USERNAME, PANORAMA_PASSWORD)
zones = network.Zone.refreshall(pano)
zones

**Comment by shinmog** [comment]
Your object hierarchy is wrong.  Panorama itself does not have zones, they're in a template.  So if you're trying to get all the zones in template "myTemplate", your code would look like this:

```python
from panos.panorama import Panorama, Template
from panos.network import Zone

pano = Panorama(....)

tmpl = Template("myTemplate")
pano.add(tmpl)

zones = Zone.refreshall(tmpl)
```

**Comment by FrancisPrakash** [comment]
It works well! Thanks :)
