### ISSUE TITLE
Need opstate documentation

### ISSUE THREAD

**Issue by shinmog** [PaloAltoNetworks/pan-os-python#396]
The opstate stuff works differently from all other pan-os-python objects.  This area needs some docs specific to it so that users know how to interact with it.

#320 
#370

**Comment by shinmog** [comment]
As a "answer my question now" measure before the docs are in place:

```python
rule.opstate.audit_comment.update("This is my audit comment")
```

The above is applicable both if the rule is new or if the rule is being modified.

**Comment by ryanbe15** [comment]
Can you please show an example of code that would update a single rule named "Int to Ext" with a new audit comment using the opstate you mentioned above?

**Comment by shinmog** [comment]
Firewall example where the rule needs to be created:

```python
from panos.firewall import Firewall
from panos.policies import Rulebase, SecurityRule

fw = Firewall(.......)

base = Rulebase()
fw.add(base)

rule = SecurityRule("Int to Ext", .......)
base.add(rule)

rule.create()
rule.opstate.audit_comment.update("This is my audit comment")
```

Panorama example where the rule already exists in device group `"myDg"`'s pre-rulebase:

```python
from panos.panorama import Panorama, DeviceGroup
from panos.policies import PreRulebase, SecurityRule

pano = Panorama(.........)

dg = DeviceGroup("myDg")
pano.add(dg)

base = PreRulebase()
dg.add(base)

rule = SecurityRule("Int to Ext")
base.add(rule)
rule.refresh()

# Make any updates needed to the rule here.
rule.description = "My new description"

rule.apply()
rule.opstate.audit_comment.update("Made some updates to the rule")
```

**Comment by ryanbe15** [comment]
I'll give it a shot.  Appreciate it.
