### ISSUE TITLE
lacp_passive_pre_negotiation wrong path with 10.1

### ISSUE THREAD

**Issue by xlp** [PaloAltoNetworks/pan-os-python#406]
## Describe the bug

With Panorama 10.1, I can not use lacp_passive_pre_negotiation since the path seems to have changed.
"msg": "Failed apply:  ae1 -> layer3 -> lacp -> passive-pre-negotiation unexpected here\n ae1 -> layer3 -> lacp is invalid"

I don't know if this worked on previous versions.

## Expected behavior

Enabling lacp_passive_pre_negotiation should not throw an error.

## Possible solution

In network.py, change
`path="{mode}/lacp/passive-pre-negotiation",`
to
`path="{mode}/lacp/high-availability/passive-pre-negotiation",`  

## Your Environment

- Version used:
  - pan-os-python 1.6.0
  - Panorama 10.1.3-h1

**Comment by shinmog** [comment]
Cross-referencing this with pango, this seems to be the wrong path for all versions, so no path changes are not an issue.
