### ISSUE TITLE
Getting objects in DeviceGroup Hierarchy based

### ISSUE THREAD

**Issue by FrancisPrakash** [PaloAltoNetworks/pan-os-python#412]
Hi

For example,
Lets have Devicegroup hierarchy level in Panorama are as below,

-- Base
----childbase1
------childbase2

When I try to refreshall objects from childbase2, it should return objects from Base, childbase1, childbase2 (maybe shared as well).

I kinda stuck in this stage, How can it be achieved through panospython ?

**Comment by alexortize** [comment]
I'm pretty sure you will need to do this yourself based on the device group hierarchy. The SDK refreshes the objects it finds in the XML at the specific device group only which doesn't include the objects defined at the parent level.

**Comment by shinmog** [comment]
To get the device group hierarchy itself, you can use either `panos.panorama.Panorama.opstate.dg_hierarchy` or `panos.panorama.DeviceGroup.opstate.dg_hierarchy`.  But @alexortize is right, if you are looking for the config stored in the parent device groups, you'll need to do refreshes in those locations to get their config.  So if you care about address objects, then:

```python
from panos.panorama import Panorama, DeviceGroup
from panos.objects import AddressObject

pano = Panorama(..............)

dg = DeviceGroup("my device group name here")
pano.add(dg)

hierarchy = dg.opstate.dg_hierarchy.fetch()
if dg.name not in hierarchy:
    raise ValueError("Device group '{0}' not in hierarchy".format(dg.name))

addrs = AddressObject.refreshall(dg)
print("Base address objects: {0}".format([x.name for x in addrs]))

parent_name = hierarchy[dg.name]
while parent_name is not None:
    dgp = DeviceGroup(parent_name)
    pano.add(dgp)

    addrs = AddressObject.refreshall(dgp)

    print("Parent '{0}' address objects: {1}".format(dgp.name, [x.name for x in addrs]))
    parent_name = hierarchy[dgp.name]
```

**Comment by rebelfish** [comment]
When running the above, I get:
`    hierarchy = dg.opstate.dg_hierarchy.fetch()
AttributeError: 'DeviceGroupHierarchy' object has no attribute 'fetch'
`

**Comment by alexortize** [comment]
Try doing like this:

from panos.panorama import DeviceGroup, Panorama, PanoramaDeviceGroupHierarchy

pan = Panorama(..............)
hierarchy = PanoramaDeviceGroupHierarchy(pan).fetch()

**Comment by rebelfish** [comment]
Using `PanoramaDeviceGroupHierarchy(pan).fetch()` works.

**Comment by shinmog** [comment]
Oops.  Was supposed to be `pano.opstate.dg_hierarchy.fetch()`

**Comment by rebelfish** [comment]
My bad... `pano.opstate.dg_hierarchy.fetch()` works. Thx!

**Comment by FrancisPrakash** [comment]
both works for me..

```
PanoramaDeviceGroupHierarchy(pano).fetch()
pano.opstate.dg_hierarchy.fetch()
```
