### ISSUE TITLE
Static route "nexthop_type" doesn't support None as PAN-OS

### ISSUE THREAD

**Issue by ysaied** [PaloAltoNetworks/pan-os-python#432]
## Describe the bug

In Static Route class (panos/network). There are no options to implement static route with "None" or Discard.  

class StaticRoute(VersionedPanObject):
... info deleted ...
    def _setup(self):
... info deleted ...
        params.append(
            VersionedParamPath(
                "nexthop_type",
                default="ip-address",
                values=["discard", "ip-address", "next-vr"],
                path="nexthop/{nexthop_type}",
            )
        )

## Expected behavior

Expected behavior is to support static routes with options for "None" and Discard. None is required to route traffic in IPSec tunnel interfaces or P2P interfaces. Discard is required to send the packet to null ..  

## Current behavior

Current behavior supports only (ip, fqdn, next-vr) next-hop. 

## Possible solution

Add None option, where NO "path="nexthop/{nexthop_type}"" is send 
Add discard option, where xpath "nexthop/discard" is send

## Steps to reproduce

Deploy static route with no next-hop like below .. 

    virtual_router = fw.add(
        pannet.VirtualRouter(
            name="default",
        )
    )
    static_route = pannet.StaticRoute(
        name="test-subnet",
        destination="10.0.0.0/24",
        interface="tunnel.100",
    )
    virtual_router.add(static_route)
    static_route.apply()

below errors is received .. 

panos.errors.PanDeviceXapiError:  routing-table -> ip -> static-route -> test-subnet -> nexthop is invalid

**Comment by shinmog** [comment]
Sometimes none in the GUI is implemented as python `None`, sometimes none is `"none"`, sometimes none is `"None"`.  In this particular case, you want to do `nexthop_type=None`, so do python `None`.

To discard, you do `nexthop_type="discard"`.
