### ISSUE TITLE
refresh_variable broken due to recent commit

### ISSUE THREAD

**Issue by clienthax** [PaloAltoNetworks/pan-os-python#444]
## Describe the bug
Commit https://github.com/PaloAltoNetworks/pan-os-python/commit/0b47a3a6afa8379cdf63d04f90f555e564e235fd changed behaviour of parse_value_from_xml_last_tag to require an additional argument 

refresh_variable does not pass the new required argument to parse_value_from_xml_last_tag here
https://github.com/PaloAltoNetworks/pan-os-python/blob/0b47a3a6afa8379cdf63d04f90f555e564e235fd/panos/base.py#L959

## Expected behavior

It to work

## Current behavior

```
  File "/usr/local/lib/python3.8/dist-packages/panos/base.py", line 970, in refresh_variable
    var_path.parse_value_from_xml_last_tag(obj, settings)
TypeError: parse_value_from_xml_last_tag() missing 1 required positional argument: 'attr'
```
## Possible solution

Add the missing argument to the caller

## Steps to reproduce

Use pan-os-ansible to gather facts from a host.

## Context

Gathering facts from network devices using ansible

## Your Environment

- Version used:  https://github.com/PaloAltoNetworks/pan-os-python/commit/ab4d088e9f231889ef25b926827e77d75d47d6cb
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): N/A
- Operating System and version (desktop or mobile): N/A
- Link to your project: N/A

**Comment by jhlasnik** [comment]
I also hit this same issue, rolling back to [v1.6.0](https://github.com/PaloAltoNetworks/pan-os-python/releases/tag/v1.6.0) has resolved my issue for the time being.
