### ISSUE TITLE
Documentation is broken 

### ISSUE THREAD

**Issue by jogueber** [PaloAltoNetworks/pan-os-python#542]
## Documentation rending broken!
Seems to be a rendering issue

https://pan-os-python.readthedocs.io/en/latest/module-firewall.html

**Comment by jogueber** [comment]
Bug

**Comment by F1p** [comment]
Any update? It's annoying

**Comment by da110us** [comment]
Workaround is to select the 'stable' version (instead of 'Latest'). Bottom right corner.

**Comment by Hanyang-Luo** [comment]
Now the stable version is also not rendering for me. Does anyone else have similar issues? Any work around?

**Comment by nikolay-matveev-kkr** [comment]
Same here… The stable branch was the workaound, and now it’s gone too.

**Comment by Hanyang-Luo** [comment]
The work around I found right now is to look into the source code. I am guessing how readTheDocs render the doc is by extracting the text string in each method. For example, I want to lookup the function "refresh_devices()" under panorama object. I can find the specification of input and output in the funciton header.

![image](https://github.com/PaloAltoNetworks/pan-os-python/assets/106833273/42145bbe-c1e2-4a37-a8ca-c3e9792205e3)

It is annoying that we can't find all the method documentation in one place but this is better than nothing.

**Comment by jamesholland-uk** [comment]
Hi everyone, apologies for the current issue with the docs. Just to let you know that the team are aware of the issue and will be progressing a fix as soon as possible

**Comment by BatD2** [comment]
Still not working - neither for latest, nor for stable release

**Comment by btorresgil** [comment]
Fixed and deployed. Sorry this took so long.

**Comment by BatD2** [comment]
@btorresgil It still seems to not be fully working. It shows the relational diagrams, but missing the actual description of each object.

**Comment by Hanyang-Luo** [comment]
I am experiencing the same issue. The detail documentation of object, methods, and class were not accessible.
